spring:
  application:
    name: store
  datasource:
    url: jdbc:mariadb://localhost:3306/store?createDatabaseIFNotExist=true
    username: store_user
    password: Bhanuka12
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

strip:
  apiURL: https://api.strip.com
  enabled: true
  timeout: 1000
  supported-currencies: USD , EUR , GBP

payment: strip

email:
  Host: smtp.gmail.com
  port: 465